### PR TITLE
Remove additional text for ok and fail state

### PR DESCRIPTION
**Pull request by jxltom**
Closes https://github.com/sarugaku/vistir/issues/35

### CODE REVIEW

**Comment by jxltom** [comment]
Besides, output of ```pipenv --python 3.6.6``` command becomes better.

From:

```
➜  test pipenv --python 3.6.6
Virtualenv already exists!
Removing existing virtualenv...
Creating a virtualenv for this project...
Pipfile: /home/user/Documents/dev/test/Pipfile
Using /home/user/.pyenv/versions/3.6.6/bin/python (3.6.6) to create virtualenv...
✔ Complete Running... Running virtualenv with interpreter /home/user/.pyenv/versions/3.6.6/bin/python
Using base prefix '/home/user/.pyenv/versions/3.6.6'
New python executable in /home/user/.local/share/virtualenvs/test-cWRQ9xvV/bin/python
Installing setuptools, pip, wheel...done.
Running virtualenv with interpreter /home/user/.pyenv/versions/3.6.6/bin/python
Virtualenv location: /home/user/.local/share/virtualenvs/test-cWRQ9xvV
```
becomes:

```
➜  test pipenv --python 3.6.6
Virtualenv already exists!
Removing existing virtualenv...
Creating a virtualenv for this project...
Pipfile: /home/user/Documents/dev/test/Pipfile
Using /home/user/.pyenv/versions/3.6.6/bin/python (3.6.6) to create virtualenv...
✔ Complete 
Using base prefix '/home/user/.pyenv/versions/3.6.6'
New python executable in /home/user/.local/share/virtualenvs/test-cWRQ9xvV/bin/python
Installing setuptools, pip, wheel...done.
Running virtualenv with interpreter /home/user/.pyenv/versions/3.6.6/bin/python
Virtualenv location: /home/user/.local/share/virtualenvs/test-cWRQ9xvV
```

The ```✔ Complete Running... Running virtualenv with interpreter /home/user/.pyenv/versions/3.6.6/bin/python``` should just be ```✔ Complete ```

**Comment by techalchemy** [comment]
If this works it looks good to me, thanks!

**Comment by jxltom** [comment]
I've tested with several pipenv commands: ```pipenv --python```, ```pipenv install```, ```pienv lock``` as well as ```pipenv lock``` with ```CTRL+C```.

They all works fine. Please have a try in case there is anything I missed.

**Comment by techalchemy** [comment]
It's such a minor change, I can't really see it breaking anything.  Thanks!

**Comment by jxltom** [comment]
:handshake:

**Pull request merged**
